const state = { devices: [], device: null, apps: [], app: null, capabilities: [], sessionId: null, samples: [], startedAt: null, stream: null, devicePoll: null, reportPoll: null };
const $ = (id) => document.getElementById(id);

async function api(path, options = {}) { const response = await fetch(path, { headers: { 'Content-Type': 'application/json' }, ...options }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Agent request failed'); return data; }
function setView(view) { document.querySelectorAll('.view').forEach((el) => el.classList.remove('active-view')); $(`${view}-view`).classList.add('active-view'); document.querySelectorAll('.nav-item').forEach((el) => el.classList.toggle('active', el.dataset.view === view)); const titles = { overview: '监测首页', devices: '设备管理', monitor: '实时监控', reports: '检测报告', settings: '系统设置' }; $('page-title').textContent = titles[view]; if (view === 'devices') renderDevicesTable(); if (view === 'reports') renderReports(); }
function renderDevices() { const list = $('device-list'); if (!state.devices.length) { list.innerHTML = '<div class="empty-state">未检测到设备，请检查 USB / ADB 连接</div>'; $('device-state').textContent = '未连接'; $('device-state').className = 'state-badge waiting'; if (state.sessionId && $('monitor-view').classList.contains('active-view')) markDisconnected(); return; } $('device-state').textContent = '已连接'; $('device-state').className = 'state-badge available'; list.innerHTML = state.devices.map((device, index) => `<div class="device-card ${index === 0 ? 'selected' : ''}" data-device="${device.id}"><div class="device-icon">▯</div><div><strong>${device.name}</strong><small>${device.version} · ${device.connection}</small></div><div class="device-meta"><b>● ONLINE</b><small>${device.id.slice(0, 12)}…</small></div></div>`).join(''); document.querySelectorAll('.device-card').forEach((card) => card.addEventListener('click', () => selectDevice(card.dataset.device))); if (!state.device || !state.devices.some((device) => device.id === state.device.id)) selectDevice(state.devices[0].id); }
async function selectDevice(id) { state.device = state.devices.find((device) => device.id === id); document.querySelectorAll('.device-card').forEach((card) => card.classList.toggle('selected', card.dataset.device === id)); $('connection-pill').textContent = `${state.device.name} · Agent 已连接`; $('connection-pill').className = 'pill'; const result = await api(`/api/v1/devices/${encodeURIComponent(id)}/applications`); state.apps = result.applications; renderApps(); }
function renderApps() { const query = $('app-search').value.toLowerCase(); const apps = state.apps.filter((app) => `${app.name} ${app.bundle}`.toLowerCase().includes(query)).slice(0, 40); $('app-list').innerHTML = apps.length ? apps.map((app) => `<label class="app-row"><input type="radio" name="app" value="${app.bundle}"><div><strong>${app.name}</strong><small>${app.bundle} · ${app.version}</small></div></label>`).join('') : '<div class="empty-state">当前设备没有匹配的用户应用</div>'; document.querySelectorAll('input[name="app"]').forEach((input) => input.addEventListener('change', () => selectApp(input.value))); }
async function selectApp(bundle) { state.app = state.apps.find((app) => app.bundle === bundle); const result = await api('/api/v1/capabilities', { method: 'POST', body: JSON.stringify({ deviceId: state.device.id, bundle }) }); state.capabilities = result.indicators; renderCapabilities(); $('start-button').disabled = !result.ready; }
function renderCapabilities() { $('capability-list').innerHTML = state.capabilities.map((item) => `<div class="capability-row"><i class="${item.state === 'degraded' ? 'degraded' : ''}"></i><b>${item.label}</b><span>${item.state === 'available' ? '可用' : '降级'} · ${item.source}</span></div>`).join(''); }
function renderDevicesTable() { $('devices-table').innerHTML = state.devices.map((device) => `<div class="device-card"><div class="device-icon">▯</div><div><strong>${device.name}</strong><small>${device.model} · ${device.version} · ${device.connection}</small></div><div class="device-meta"><b>● 已连接</b><small>${device.id}</small></div></div>`).join('') || '<div class="empty-state">暂无设备</div>'; }
async function startSession() { if (!state.device || !state.app) return; const created = await api('/api/v1/sessions', { method: 'POST', body: JSON.stringify({ device: state.device, bundle: state.app.bundle }) }); state.sessionId = created.sessionId; state.samples = []; state.startedAt = Date.now(); await api(`/api/v1/sessions/${state.sessionId}/start`, { method: 'POST', body: '{}' }); $('monitor-app').textContent = state.app.name; $('monitor-device').textContent = `${state.device.name} · ${state.device.version} · ${state.app.bundle}`; $('monitor-capabilities').innerHTML = state.capabilities.map((item) => `<div class="coverage-item"><i class="${item.state === 'degraded' ? 'degraded' : ''}"></i>${item.label}<span>${item.state === 'available' ? '可用' : '降级'}</span></div>`).join(''); setView('monitor'); state.stream = new EventSource(`/api/v1/sessions/${state.sessionId}/stream`); state.stream.onmessage = (message) => handleEvent(JSON.parse(message.data)); state.stream.onerror = () => { if (state.sessionId) markDisconnected(); }; clearInterval(state.devicePoll); state.devicePoll = setInterval(checkDeviceConnection, 2500); }
function handleEvent(event) { if (event.type === 'sample') { state.samples.push(event.data); updateMetrics(event.data); drawCharts(); } if (event.type === 'status') { $('monitor-status').textContent = event.data.status === 'completed' ? '监测完成' : '采集异常'; } if (event.type === 'error') addEvent('采集失败', event.data.message); }
function markDisconnected() { if (!$('monitor-view').classList.contains('active-view')) return; $('monitor-status').textContent = '设备已断开'; $('monitor-status').className = 'disconnected-label'; $('monitor-status').style.color = '#c65345'; $('connection-pill').textContent = '设备已断开'; $('connection-pill').className = 'pill disconnected'; $('connection-pill').style.background = '#ffe8e4'; $('connection-pill').style.color = '#c65345'; $('stop-button').disabled = true; addEvent('设备断开', '已停止继续接收采样，当前数据已保留'); if (state.stream) state.stream.close(); clearInterval(state.devicePoll); watchReport(); }
async function checkDeviceConnection() { try { const result = await api('/api/v1/devices'); state.devices = result.devices; if (!state.device || !result.devices.some((device) => device.id === state.device.id)) markDisconnected(); } catch (error) { markDisconnected(); } }
function updateMetrics(sample) { const nums = state.samples; const fps = nums.map((x) => x.fps).filter(Number.isFinite); const memory = nums.map((x) => x.memory).filter(Number.isFinite); $('fps-value').textContent = Number.isFinite(sample.fps) ? sample.fps.toFixed(1) : '--'; $('fps-average').textContent = fps.length ? (fps.reduce((a, b) => a + b, 0) / fps.length).toFixed(1) : '--'; $('fps-min').textContent = fps.length ? Math.min(...fps).toFixed(1) : '--'; $('cpu-value').textContent = Number.isFinite(sample.cpu) ? `${sample.cpu.toFixed(1)}%` : '--'; $('cpu-bar').style.width = `${Math.min(sample.cpu || 0, 100)}%`; $('memory-value').textContent = Number.isFinite(sample.memory) ? `${sample.memory.toFixed(1)} MB` : '--'; $('memory-peak').textContent = memory.length ? `${Math.max(...memory).toFixed(1)} MB` : '--'; $('gpu-value').textContent = Number.isFinite(sample.gpu) ? `${sample.gpu.toFixed(1)}%` : '不支持'; $('sample-count').textContent = nums.length; $('chart-fps-label').textContent = `${fps.length ? fps.at(-1).toFixed(1) : '--'} FPS`; $('chart-resource-label').textContent = Number.isFinite(sample.cpu) ? `${sample.cpu.toFixed(1)}% CPU` : '等待数据'; }
function drawLine(canvas, values, color, min, max) { const context = canvas.getContext('2d'); const width = canvas.clientWidth || 500; const height = canvas.height; canvas.width = width * devicePixelRatio; canvas.height = height * devicePixelRatio; context.scale(devicePixelRatio, devicePixelRatio); context.clearRect(0, 0, width, height); context.strokeStyle = '#e8efec'; context.lineWidth = 1; for (let y = 20; y < height; y += 35) { context.beginPath(); context.moveTo(0, y); context.lineTo(width, y); context.stroke(); } if (values.length < 2) return; context.strokeStyle = color; context.lineWidth = 2.5; context.beginPath(); values.forEach((value, index) => { const x = (index / Math.max(values.length - 1, 1)) * width; const y = height - ((Math.max(min, Math.min(max, value)) - min) / (max - min)) * (height - 25) - 8; index ? context.lineTo(x, y) : context.moveTo(x, y); }); context.stroke(); }
function drawCharts() { drawLine($('fps-chart'), state.samples.map((x) => x.fps).filter(Number.isFinite), '#ed775f', 0, 70); drawLine($('resource-chart'), state.samples.map((x) => x.cpu).filter(Number.isFinite), '#5f91d3', 0, 100); }
function addEvent(title, message) { $('event-count').textContent = Number($('event-count').textContent) + 1; $('event-list').insertAdjacentHTML('afterbegin', `<div class="event-item"><i></i><div><b>${title}</b><small>${message}</small></div></div>`); }
function resetMonitor() { clearInterval(state.reportPoll); if (state.stream) state.stream.close(); state.sessionId = null; state.samples = []; state.startedAt = null; $('monitor-status').textContent = '等待下一次监测'; $('monitor-status').className = 'live-label'; $('sample-count').textContent = '0'; $('fps-value').textContent = '--'; $('fps-average').textContent = '--'; $('fps-min').textContent = '--'; $('cpu-value').textContent = '--'; $('cpu-bar').style.width = '0%'; $('memory-value').textContent = '--'; $('memory-peak').textContent = '--'; $('gpu-value').textContent = '--'; $('chart-fps-label').textContent = '--'; $('chart-resource-label').textContent = '等待数据'; $('event-count').textContent = '0'; $('event-list').innerHTML = '<div class="empty-state">采集中，异常会出现在这里</div>'; drawCharts(); $('stop-button').disabled = false; }
async function renderReports() { const container = $('report-list'); if (!container) return; container.innerHTML = '<div class="empty-state">正在加载报告记录…</div>'; try { const result = await api('/api/v1/reports'); if (!result.reports.length) { container.innerHTML = '<div class="empty-state">暂无历史报告</div>'; return; } container.innerHTML = result.reports.map((report) => { const device = report.device || {}; const date = new Date((report.createdAt || 0) * 1000).toLocaleString(); const status = report.reportReady ? '报告可用' : `记录已保存 · ${report.error || '报告不可用'}`; return `<article class="report-row"><div><b>${report.bundle || '未知应用'}</b><small>${device.name || '未知设备'} · ${date}</small></div><div class="report-row-meta"><span>${status}</span>${report.reportReady ? `<button class="secondary-button report-open" data-session="${report.sessionId}">打开报告</button>` : '<em>无 HTML 报告</em>'}</div></article>`; }).join(''); container.querySelectorAll('.report-open').forEach((button) => { button.addEventListener('click', () => window.open(`/api/v1/sessions/${button.dataset.session}/report`, '_blank')); }); } catch (error) { container.innerHTML = `<div class="empty-state">${error.message}</div>`; } }
async function finishSession() { if (!state.sessionId) return; const sessionId = state.sessionId; clearInterval(state.reportPoll); const started = Date.now(); while (Date.now() - started < 60000) { try { const result = await api(`/api/v1/sessions/${sessionId}`); if (result.status === 'completed' || result.status === 'failed') { const shouldOpen = window.confirm(result.reportReady ? '本次监测已记录，是否生成并查看报告？' : `本次监测记录已保存，但报告不可用。${result.error ? `\n\n原因：${result.error}` : ''}\n\n是否打开报告列表？`); if (shouldOpen) { setView('reports'); await renderReports(); } else { resetMonitor(); } return; } } catch (error) { addEvent('收尾失败', error.message); resetMonitor(); return; } await new Promise((resolve) => setTimeout(resolve, 500)); } window.confirm('报告收尾超时，已保留本次记录。点击确定返回实时监控并清空当前数据显示。'); resetMonitor(); }
async function stopSession() { if (!state.sessionId) return; $('stop-button').disabled = true; await api(`/api/v1/sessions/${state.sessionId}/stop`, { method: 'POST', body: '{}' }); $('monitor-status').textContent = '正在保存本次记录'; clearInterval(state.devicePoll); if (state.stream) state.stream.close(); await finishSession(); }
async function load() { const result = await api('/api/v1/devices'); state.devices = result.devices; renderDevices(); }
document.querySelectorAll('.nav-item').forEach((button) => button.addEventListener('click', () => setView(button.dataset.view))); $('refresh-button').addEventListener('click', load); $('app-search').addEventListener('input', renderApps); $('start-button').addEventListener('click', startSession); $('stop-button').addEventListener('click', stopSession); load().catch((error) => { $('connection-pill').textContent = 'Agent 未启动'; $('connection-pill').className = 'pill muted'; $('device-list').innerHTML = `<div class="empty-state">${error.message}</div>`; });
